extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  no-unused-vars:
    - error
    - varsIgnorePattern: '^_$'
  array-bracket-spacing:
    - error
  func-call-spacing:
    - error
  space-in-parens:
    - error
  comma-spacing:
    - error
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
