env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
parser: '@babel/eslint-parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
rules:
  react/prop-types:
    - off
