name: Update web player
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the environment
        run: |
          git config --global user.email 'null'
          git config --global user.name 'bot'
          echo 'repo_url=https://x-token-auth:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git' >> "$GITHUB_ENV"
      - name: Clone the repository
        run: |
          git clone "$repo_url" root/
      - name: Install development dependencies
        working-directory: root/
        run: |
          npm install
      - name: Build the web player
        working-directory: root/
        run: |
          npm run prepack
      - name: Push the result in a separate branch
        working-directory: root/
        run: |
          cd dist
          git init
          git add .
          git commit --message 'Update the web player @ ${{ github.sha }}'
          git push --force "$repo_url" master:player
